title: The Reading Dimension
email: readandprogress@duck.com
description: >- # this means to ignore newlines until "baseurl:"
  My online portal of sorts, I maintain a blog here, as well as some other projects of mine.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Reading
favicon: /favicon.png
show_excerpts: true

feed:
  path: blog/feed.xml
  title: Reading's Dimension 

# Permalink configuration
permalink: /blog/:title/

# Build settings
theme: minima
minima:
  skin: auto

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
